
### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profiles:
    active: development
  # IDENTITY (ContextIdApplicationContextInitializer)
  application:
    name: csos-kdn-ev
    index: index

  # boot:
  #   admin:
  #     url: http://localhost:8088

  # Hibernate
  # validate | update | create | create-drop
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    generate-ddl: true

  # DataSource
  datasource:
    # name= # name of the data source
    # initialize=true # populate using data.sql
    # schema= # a schema (DDL) script resource reference
    # data= # a data (DML) script resource reference
    # sqlScriptEncoding= # a charset for reading SQL scripts
    # platform= # the platform to use in the schema resource (schema-${platform}.sql)
    continueOnError: false
    separator: ;
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.17/STOCMS
    username: yjchoi
    password: yjchoi1234
    max-active: 100
    max-idle: 8
    min-idle: 8
    initial-size: 10
    validation-query: SELECT 1
    test-on-borrow: false
    test-on-return: false
    # test-while-idle:
    # time-between-eviction-runs-millis:
    # min-evictable-idle-time-millis:
    # max-wait:

    # csos database configuration
    csos:
      platform: mysql
      url: jdbc:mysql://192.168.10.17/JPA_TEST
      username: yjchoi
      password: yjchoi1234
      driver-class-name: com.mysql.jdbc.Driver
      continueOnError: true
      initialize: true

    # admin database configuration
    admin:
      platform: mysql
      url: jdbc:mysql://192.168.10.17/JPA_ADMIN_TEST
      username: yjchoi
      password: yjchoi1234
      driver-class-name: com.mysql.jdbc.Driver
      continueOnError: true
      initialize: false

  # JMX
  jmx:
    enabled: true

  # ACTIVEMQ (ActiveMQProperties)
  activemq:
    broker-url: tcp://192.168.10.17:61616
    user:
    password:
    in-memory: true
    pooled: false

  # JMS (JmsProperties)
  # spring.jms.pub-sub-domain= # false for queue (default), true for topic
  jms:
    queue:
      destination: INPUT.CSOS.>

  mybatis:
    basePackage: com.kdn.csos.engine.repository.mapper

# LOGGING
logging:
  # path: ./logs/
  # file: myapp.log # cannot set file, path at the same time.
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  # config: log4j2.xml

server:
  port: 9000

# Management
# management.security.enabled=false
management:
  port: 8081
  address: 127.0.0.1
  context-path: /manage

endpoints:
  health:
    enabled: true
  jmx:
    domain: myapp
    unique-names: true

